package cop5556fa18;

import static org.junit.Assert.assertEquals;

import java.io.FileOutputStream;
import java.io.OutputStream;
import java.lang.reflect.Method;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import cop5556fa18.PLPAST.Program;
import cop5556fa18.PLPCodeGenUtils.DynamicClassLoader;

public class PLPCodeGenTest {	
	//determines whether show prints anything
		static boolean doPrint = true;
		
		static void show(Object s) {
			if (doPrint) {
				System.out.println(s);
			}
		}

		//determines whether a classfile is created
		static boolean doCreateFile = false;
		
		@Rule
		public ExpectedException thrown = ExpectedException.none();
		

		//values passed to CodeGenerator constructor to control grading and debugging output
		private boolean devel = true; //if true, print devel output
		private boolean grade = true; //if true, print grade output
		
		/**
		 * Generates bytecode for given input.
		 * Throws exceptions for Lexical, Syntax, and Type checking errors
		 * 
		 * @param input   String containing source code
		 * @return        Generated bytecode
		 * @throws Exception
		 */
		byte[] genCode(String input) throws Exception {
			
			//scan, parse, and type check
			PLPScanner scanner = new PLPScanner(input);
			show(input);
			scanner.scan();
			PLPParser parser = new PLPParser(scanner);
			Program program = parser.parse();
			PLPTypeChecker v = new PLPTypeChecker();
			program.visit(v, null);
//			show(program);  //It may be useful useful to show this here if code generation fails

			//generate code
			PLPCodeGen cv = new PLPCodeGen(null, devel, grade);
			byte[] bytecode = (byte[]) program.visit(cv, null);
			show(program); //doing it here shows the values filled in during code gen
			//display the generated bytecode
			show(PLPCodeGenUtils.bytecodeToString(bytecode));
			
			//write byte code to file 
			if (doCreateFile) {
				String name = ((Program) program).name;
				String classFileName = "bin/" + name + ".class";
				OutputStream output = new FileOutputStream(classFileName);
				output.write(bytecode);
				output.close();
				System.out.println("wrote classfile to " + classFileName);
			}
			
			//return generated classfile as byte array
			return bytecode;
		}
		
		/**
		 * Run main method in given class
		 * 
		 * @param className    
		 * @param bytecode    
		 * @param commandLineArgs  String array containing command line arguments, empty array if none
		 * @throws + 
		 * @throws Throwable 
		 */
		void runCode(String className, byte[] bytecode) throws Exception  {
			PLPRuntimeLog.initLog(); //initialize log used for grading.
			DynamicClassLoader loader = new DynamicClassLoader(Thread.currentThread().getContextClassLoader());
			Class<?> testClass = loader.define(className, bytecode);
			String[] commandLineArgs = {};
			@SuppressWarnings("rawtypes")
			Class[] argTypes = {commandLineArgs.getClass()};
			Method m = testClass.getMethod("main", argTypes );
			show("Output from " + m + ":");  //print name of method to be executed
			Object passedArgs[] = {commandLineArgs};//create array containing params, in this case a single array.
			//show(passedArgs);
			try {
			m.invoke(null, passedArgs);	
			}
			catch (Exception e) {
				Throwable cause = e.getCause();
				if (cause instanceof Exception) {
					Exception ec = (Exception) e.getCause();
					throw ec;
				}
				throw  e;
			}
		}
		
		/**
		 * Since we are not doing any optimization, the compiler will 
		 * still create a class with a main method and the JUnit test will
		 * execute it.  
		 * 
		 * The only thing it will do is append the "entering main" and "leaving main" messages to the log.
		 * 
		 * @throws Exception
		 */
		@Test
		public void emptyProg() throws Exception {
			String prog = "emptyProg";	
			String input = prog + "{}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void integerLit() throws Exception {
			String prog = "intgegerLit";
			String input = prog + "{string s =  \"sfs\"+\"ff\";print s;} ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;sfsff;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void test1() throws Exception {
			String prog = "test1";	
			String input = prog + "{int a=5;while(a>1){a=a-1;};print a;}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;1;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void test2() throws Exception {
			String prog = "test2";	
			String input = prog + "{int x,b,c,d;}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		
		
		@Test
		public void test3() throws Exception {
			String prog = "test3";	
			String input = prog + "{char c = 's';int x =1; print x;}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;1;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		@Test
		public void test4() throws Exception {
			String prog = "test4";	
			String input = prog + "{boolean a = 3>4;print a;}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;false;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void tests4() throws Exception {
			String prog = "test4";	
			String input = prog + "{\n"
				     + "    int a = 10;\n"
					 + "        if (a != 15) {\n"
				     + "            a = a + 1;\n"
					 + "        };\n"
				     + "}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void test5() throws Exception {
			String prog = "test5";	
			String input = prog + "{\n"
				     + "    int c = 5;\n"
					 + "    float a = 5.0;\n"
					 + "    boolean e = true;\n"
					 + "    char f = 'a';\n"
					 + "    int h, i, j;\n"
					 + "    float k;\n"
				     + "}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void test6() throws Exception {
			String prog = "test6";	
			String input = prog + "{\n"
				     + "    int a = 10;\n"
					 + "    int b = 1;\n"
				     + "    int c = 0;\n"
				     + "    if (a > (b & c)) {\n"
					 + "        while (a > 0) {\n"
				     + "            a = a - 1;\n"
					 + "        };\n"
				     + "    };\n"
					 + "    a = 100;\n"
				     + "    print \"I love computer science!\";\n"
				     + "}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;I love computer science!;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void test7() throws Exception {
			String prog = "test7";	
			String input = prog + "{int a=1;int y=2; a = y; print a;}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;2;leaving main;",PLPRuntimeLog.globalLog.toString());
		}

		@Test
		public void test8() throws Exception {
			String prog = "test8";	
			String input = prog + "{char s = \'s\';s = \'d\';print s;}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;d;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
//		@Test
//		public void test9() throws Exception {
//			String prog = "test7";	
//			String input = prog + "{int a=sin(5); print a;}";
//			byte[] bytecode = genCode(input);
//			runCode(prog, bytecode);
//			show("Log:\n "+PLPRuntimeLog.globalLog);
//			assertEquals("entering main;5;leaving main;",PLPRuntimeLog.globalLog.toString());
//		}
		
		@Test
		public void test10() throws Exception {
			String prog = "test7";	
			String input = prog + "{boolean b; b = false; print b;}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;false;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		@Test
		public void test11() throws Exception {
			String prog = "test11";	
			String input = prog + "{string s = \"sfa\";s=\"wwt\"; print s;}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;wwt;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
}
